### ISSUE TITLE
add Pkg_name: error

### ISSUE THREAD

**Issue by ghost** [JuliaComputing/JuliaProIssues#3]
Hi, I have this error when adding Makie to my test environment.
(test) pkg> add Makie
   Updating registry at `C:\Users\User\.julia\registries\JuliaComputingRegistry`
ERROR: The following package names could not be resolved:
 * Makie (not found in project, manifest or registry)
Thank you.

Brian Bennett.

**Comment by bmharsha** [comment]
Hello,

Can you try following steps and let us know if this solves your issue?

1) Navigate to following folder in "Windows file explorer": `C:\Users\User\.julia\registries\`
2) Delete following folder (If it exists) : `C:\Users\User\.julia\registries\General`
3) Open JuliaPro REPL and execute following command:

```
Pkg.Registry.add(Pkg.RegistrySpec(url = "$(Pkg.pkg_server())/registry/General", uuid = "23338594-aafe-5451-b93e-139f81909106"))
```
While the above command is being executed, if a valid auth.toml is not present, then you may be requested to authenticate in your browser.

**Comment by bmharsha** [comment]
Please reopen a new issue if you're still encountering it.
